default_context:
  project_name: 'operation'
  project_slug: 'operation'
  domain_main: 'operation.com'
  domain_staging: 'stag.operation.com'
  docker_swarm_stack_name_main: 'operation-com'
  docker_swarm_stack_name_staging: 'stag-operation-com'
  secret_key: 'test'
  first_superuser: 'admin'
  first_superuser_password: 'admin123'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.operation.com", "https://stag.operation.com", "https://operation.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@operation.com'
  postgres_password: 'admin123'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: 'admin123'
  traefik_constraint_tag: 'operation.com'
  traefik_constraint_tag_staging: 'stag.operation.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin123'
  sentry_dsn: ''
  docker_image_prefix: 'operation'
  docker_image_backend: 'operationbackend'
  docker_image_celeryworker: 'operationceleryworker'
  docker_image_frontend: 'operationfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
